"""
Cold Email Writer Node implementation.
Responsible for interpreting the Company Profile generated by the researcher
and drafting a highly targeted, realistic cold email.
"""

from core.state import TreclState
from llm.model import llm
from langchain_core.messages import SystemMessage, HumanMessage

def cold_email_writer_node(state: TreclState) -> dict:
    """
    LangGraph node representing the Writer Agent.
    
    1. Reads the `company_summary` from the graph state.
    2. Prompts the LLM to draft a realistic cold email under 150 words.
    3. Enforces that the draft leverages the extracted technical facts.
    
    Args:
        state (TreclState): The current graph state containing `company_name` and `company_summary`.
        
    Returns:
        dict: A dictionary update patch containing the `cold_email` key.
    """
    company = state["company_name"]
    research = state["company_summary"]
    
    print(f"\n✍️ Writing targeted cold email for {company}...")

    # Step 1: Build the strict writing prompt
    prompt = f"""Write a cold email from a software developer seeking an internship at {company}.
    
    Company Research:
    {research}
    
    The email MUST adhere to ALL of the following rules:
    - Subject line that references something SPECIFIC about the company's tech stack or product.
    - Be strictly under 150 words.
    - Reference ONE specific technical detail from the research (e.g. mention their DB, language, or scaling problem).
    - Propose ONE specific contribution based on their likely technical challenges.
    - End with a clear, direct, and polite ask.
    
    Format output strictly as:
    SUBJECT: [subject line]
    
    [email body]"""

    messages = [
        SystemMessage(content="You are an elite, highly effective B2B tech recruiter and cold email strategist. You write concise, high-converting outreach messages."),
        HumanMessage(content=prompt)
    ]
    
    # Step 2: Generate Draft
    response = llm.invoke(messages)
    
    print("\n✅ Draft Complete.")
    return {"cold_email": response.content}
