"""
Cold Email Writer Node implementation.
Responsible for interpreting the Company Profile generated by the researcher
and drafting a highly targeted, realistic cold email.
"""

from core.state import TreclState
from llm.model import llm
from langchain_core.messages import SystemMessage, HumanMessage

def cold_email_writer_node(state: TreclState) -> dict:
    """
    LangGraph node representing the Writer Agent.
    
    1. Extracts the custom project pitch and ranked pain points from the state.
    2. Uses a strict prompt to write a highly targeted, 150-word cold email.
    
    Args:
        state (TreclState): The current graph state.
        
    Returns:
        dict: A dictionary update patch containing the `cold_email` key.
    """
    company = state["company_name"]
    pain_points = state.get("pain_points_ranked", "No pain points found.")
    project = state.get("project_ideas", "No project idea found.")
    
    print(f"\n[~] Writing targeted cold email for {company}...")

    # Step 1: Build the strict writing prompt
    prompt = f"""Write a compelling cold email from a software developer seeking an internship or role at {company}.
    
    Company's Top Pain Points:
    {pain_points}
    
    My Proposed Custom Project:
    {project}
    
    The email MUST adhere to ALL of the following rules:
    - Subject line that references the core technical value proposition of my project.
    - Be strictly under 150 words.
    - Assert that you have thoroughly researched their engineering needs.
    - Propose the EXACT project listed above as a way you can add immediate value.
    - End with a clear, direct, and polite call to action (e.g., asking for a 10-minute chat).
    
    Format output strictly as:
    SUBJECT: [subject line]
    
    [email body]"""

    messages = [
        SystemMessage(content="You are an elite, highly effective B2B tech recruiter and cold email strategist. You write concise, high-converting outreach messages."),
        HumanMessage(content=prompt)
    ]
    
    # Step 2: Generate Draft
    response = llm.invoke(messages)
    
    print("\n[+] Draft Complete.")
    return {"cold_email": response.content}
